# Generated by Django 3.0.2 on 2020-01-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200107_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='painting_date',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
