# Generated by Django 3.0.2 on 2020-01-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200107_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
