# Generated by Django 3.0.2 on 2020-01-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_painting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=models.DateTimeField(auto_now=True)),
        ),
    ]
