# Generated by Django 3.0.2 on 2020-01-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200108_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='paintings',
            field=models.ManyToManyField(blank=True, to='api.Painting'),
        ),
    ]
